name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (latest)
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: mantisadnetwork/mantis-mongo:latest

      - name: Build and Push (commit)
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: mantisadnetwork/mantis-mongo:${{ github.sha }}

#  deploy:
#    runs-on: ubuntu-24.04
#    needs: build
#    if: ${{ github.ref == 'refs/heads/master' }}
#    strategy:
#      matrix:
#        region: [ east ]
#    steps:
#      - name: Create kubeconfig
#        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
#
#      - name: Update container image
#        run: |
#          kubectl \
#          --kubeconfig=kubeconfig.yaml \
#          --context=production_${{ matrix.region }} \
#          patch $(kubectl --kubeconfig=kubeconfig.yaml --context=production_${{ matrix.region }} get cronjob -o name) \
#          --patch '{"spec": {"jobTemplate": {"spec": {"template": {"spec": {"containers": [{"name":"node","image": "mantisadnetwork/mantis-cron:${{ github.sha }}"}]}}}}}}'
